---
- name: homebrew | download Homebrew install script
  get_url:
    url=https://raw.githubusercontent.com/Homebrew/install/master/install
    dest=vendor/homebrew/install

- name: homebrew | install Homebrew
  command: ruby vendor/homebrew/install creates=/usr/local/bin/brew

- name: homebrew | update Homebrew
  homebrew: update_homebrew=yes

- name: homebrew | tap brewdler
  homebrew_tap: tap=homebrew/brewdler state=present

- name: homebrew | brewdle
  command: brew brewdle chdir=roles/homebrew/files

- name: homebrew | clean up old versions
  command: brew cleanup

- name: homebrew | clean up old casks
  command: brew cask cleanup

